### ISSUE TITLE
Small FAQ nit: DirectWrite applies hinting in x-direction, FreeType's v40 doesn't

### ISSUE THREAD

**Issue by madig** [servo/font-kit#102]
> https://github.com/pcwalton/font-kit/wiki/FAQ
> For GDI, the solution is a complex series of hacks; for DirectWrite, the solution is to ignore all horizontal hinting instructions, which still amounts to a series of hacks, albeit a less complex one.

I remember reading somewhere (was it Beat Stamm?) that DirectWrite indeed applies hints on the x-axis, but, in hack-mode, with a granularity of 1/16 of a pixel instead of a full one (fonts can still do whatever they want in native ClearType mode!). Or something. I chose to ignore x-axis changes in the v40 engine because the results are more or less the same.

**Comment by pcwalton** [comment]
Interesting, thanks!

**Comment by pcwalton** [comment]
Updated with a link to this issue.
