### ISSUE TITLE
RUSTSEC-2020-0053: dirs: dirs is unmaintained, use dirs-next instead

### ISSUE THREAD

**Issue by brightly-salty** [servo/font-kit#173]
After running `cargo audit` on my project, which has a transient dependence on font-kit, I got the following security advisory concerning the `dirs` dependency:
```
Crate:         dirs
Version:       2.0.2
Warning:       unmaintained
Title:         dirs is unmaintained, use dirs-next instead
Date:          2020-10-16
ID:            RUSTSEC-2020-0053
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0053
Dependency tree:
dirs 2.0.2
└── font-kit 0.8.0
```
From the [website](https://rustsec.org/advisories/RUSTSEC-2020-0053), `dirs-next` would be a good replacement (I think drop-in?). I do realize this is a previous release, but I checked the current release, and `dirs` is still depended upon for some architectures.

**Comment by jdm** [comment]
Want to make a pull request?

**Comment by brightly-salty** [comment]
Sure, I can try to attempt it.
