### ISSUE TITLE
Need to update `pathfinder_simd`

### ISSUE THREAD

**Issue by pbdeuchler** [servo/font-kit#233]
Due to the recent nightly `stdsimd` changes the dependency `pathfinder_simd` needs an update in order to build `font-kit`

https://github.com/servo/pathfinder/issues/550

**Comment by jayvdb** [comment]
Note https://github.com/servo/font-kit/pull/227 did some prep for a new release

**Comment by atouchet** [comment]
pathfinder_simd has now been updated.

**Comment by jayvdb** [comment]
Not yet
