### ISSUE TITLE
How to get bounding box that encloses all glyphs from the font?

### ISSUE THREAD

**Issue by katyo** [servo/font-kit#29]
I would like to get bbox for glyphs of font as described at https://www.freetype.org/freetype2/docs/glyphs/glyphs-3.html#section-2

Is there any way to do it?

**Comment by pcwalton** [comment]
The problem here is that the API to do this is Windows 8 only, so we need to implement it ourselves on Windows 7. I should just do that.

**Comment by pcwalton** [comment]
I have a PR ready to go, but it needs a `dwrote-rs` upgrade first.
