### ISSUE TITLE
Use a thinner fontconfig crate

### ISSUE THREAD

**Issue by RazrFalcon** [servo/font-kit#31]
`servo-fontconfig` is pretty heavy (as a build dependency), since it uses bundled C sources:

- servo-fontconfig - 1.7MiB
- servo-freetype-sys - 1.8MiB
- expat-sys - 0.5MiB

So to build font-kit on Linux we have to download ~4MiB of useless code, because it will use system libraries anyway.

There are no alternatives for now, but it's still a problem, imho.

**Comment by pcwalton** [comment]
Do we know why those upstream libraries do that? Should they just not build any C source on Linux?

**Comment by RazrFalcon** [comment]
They don't. But they still bundle sources. I guess it can be fixed by moving sources into a separate crate and hide it behind a feature. Then there will be no need to download it on Linux.

**Comment by jayvdb** [comment]
This issue can probably be closed as font-kit uses `yeslogic-fontconfig-sys` now, and `servo-fontconfig` is archived
