### ISSUE TITLE
No acccess to device horizontal metrics

### ISSUE THREAD

**Issue by raphlinus** [servo/font-kit#32]
This is actually an architectural question about whether layout based on font-kit should be sensitive to font-size or whether layout should be considered scale-invariant and scaling should strictly be a rendering question.

In any case, the `advance` method on `Font` only gives access to font-unit advance, without any way to access the `hdmx` table.

**Comment by pcwalton** [comment]
I think layout needs to be considered scale-invariant.

We now have access to the `hdmx` table via `load_font_table`, so I'm going to close this for now. Feel free to reopen if there's anything for `font-kit` to do.
