### ISSUE TITLE
Consider separating font rendering and font matching into separate crates

### ISSUE THREAD

**Issue by jrmuizel** [servo/font-kit#89]
WebRender and Raqote don't need any of the font matching/searching code so it would be nice to have a separate font rendering crate.

**Comment by RazrFalcon** [comment]
I agree that font matching can be moved to a subcrate.

**Comment by RazrFalcon** [comment]
@jrmuizel it's actually not that simple, since a matching algorithm loads the font files to query some metadata. So it needs the loader part.

**Comment by pcwalton** [comment]
@jrmuizel How about putting matching and rendering behind feature flags?

**Comment by jrmuizel** [comment]
Sure. That would be an improvement.

**Comment by pcwalton** [comment]
There's now a `source` feature. If you leave it out, then sources will be excluded entirely. Feel free to reopen if you need more than this.
